package com.hcwins.vehicle.ta.acp.sampler.data;

import com.hcwins.vehicle.protocol.util.Utils;

/**
 * Created by tommy on 4/18/15.
 */
public abstract class AbstractACPMessageData implements ACPMessageData {
    protected int index = 0;

    protected byte[] currentMessageData;

    public AbstractACPMessageData() {
        //
    }

    public int getIndex() {
        return index;
    }

    public void increaseIndex() {
        this.index++;
    }

    @Override
    public byte[] generateMessageData() {
        increaseIndex();

        setCurrentMessageData(String.format("this message is generated by AbstractACPMessageData - %d", getIndex()).getBytes());

        return getCurrentMessageData();
    }

    @Override
    public byte[] getCurrentMessageData() {
        return currentMessageData;
    }

    public void setCurrentMessageData(byte[] currentMessageData) {
        this.currentMessageData = currentMessageData;
    }

    @Override
    public String getCurrentMessageDataAsByteString() {
        return Utils.byteToStr(getCurrentMessageData());
    }

    @Override
    public String getCurrentMessageDataAsReadableString() {
        return new String(getCurrentMessageData());
    }
}
